// XAML islands need a manual entry point that calls XamlCheckProcessRequirements()
// before initializing the WinUI host. Generated by Microsoft.WindowsAppSDK
// templates; see https://learn.microsoft.com/windows/apps/winui/winui3/.

using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;

namespace MailMCP;

internal static class Program
{
    [global::System.STAThread]
    private static void Main(string[] args)
    {
        ComWrappersSupport.InitializeComWrappers();
        Microsoft.UI.Xaml.Application.Start((p) =>
        {
            var context = new DispatcherQueueSynchronizationContext(
                DispatcherQueue.GetForCurrentThread());
            global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
            _ = new App();
        });
    }
}
